# Navigation Links
#   Weight parameter defines the order (use multiples of 10 for easier reordering)

main:
  - name: Home
    url: /
    weight: 10
  - name: Publications
    url: /publication/
    weight: 20
  - name: Projects
    url: /projects/
    weight: 30
  - name: Experience
    url: /experience/
    weight: 40
  - name: Blog
    url: /post/
    weight: 50
