############################
## HUGO MODULES
## Install or uninstall themes and plugins here.
## Docs: https://gohugo.io/hugo-modules/
############################

mounts:
  - source: layouts
    target: layouts
  - source: assets
    target: assets
  - source: blox
    target: layouts/_partials/hbx/blocks
    files:
      - '**/block.html'
  - source: blox
    target: assets/js/hbx/blocks
    files:
      - '**/*.js'
      - '**/*.ts'
      - '**/*.jsx'
      - '**/*.tsx'
  - source: blox
    target: assets/css/hbx/blocks
    files:
      - '**/*.css'
  - source: blox/shared/js
    target: assets/js/hbx/shared
  - source: blox/shared/css
    target: assets/css/hbx/shared
